debug: true

server:
  port: 5000

spring:
  security:
    user:
      name: rami
      password: r@123

  datasource:
    core:
      jdbc-url: jdbc:postgresql://localhost:5432/mpt_core
      username: myuser
      password: mypassword
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    # locations: classpath:db/migration/core

logging:
  level:
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: OFF

